[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/horizons"
  to = "/.netlify/functions/horizons"
  status = 200
  force = true

[[redirects]]
  from = "/api/telemetry"
  to = "/.netlify/functions/telemetry"
  status = 200
  force = true
